name: Build iOS App (Free Mac Runner)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest  # FREE Mac runner from GitHub!
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate native project
        run: npx expo prebuild --platform ios --clean
      
      - name: Setup Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version
      
      - name: Build iOS app
        run: |
          set -euo pipefail
          mkdir -p build
          xcodebuild -workspace ios/WorkoutTracker.xcworkspace \
            -scheme WorkoutTracker \
            -configuration Release \
            -derivedDataPath build/DerivedData \
            -archivePath "$GITHUB_WORKSPACE/build/WorkoutTracker.xcarchive" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            archive
      
      - name: Package unsigned .app (not installable on device)
        run: |
          set -euo pipefail
          APP_PATH="$(ls -1 "$GITHUB_WORKSPACE/build/WorkoutTracker.xcarchive/Products/Applications/"*.app | head -n 1)"
          echo "Found app at: $APP_PATH"
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "$GITHUB_WORKSPACE/build/WorkoutTracker.app.zip"
      
      - name: Upload unsigned build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            build/WorkoutTracker.xcarchive
            build/WorkoutTracker.app.zip
          if-no-files-found: error
      
      - name: Upload IPA to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/WorkoutTracker.app.zip
            build/WorkoutTracker.xcarchive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

